apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.env }}-widget
  namespace: {{ .Values.env }}-widget
spec:
  selector:
    app: widget
  ports:
    - protocol: TCP
      port: 3082
      targetPort: 80
